image: alpine/latest
packages:
  - crystal
  - shards
  - yaml-dev
  - libxml2-dev
oauth: pages.sr.ht/PAGES:RW
environment:
  site: arcade.srht.site
sources:
  - https://git.sr.ht/~arcade/nebula
tasks:
- setup: |
    mkdir bin
    wget https://github.com/makeworld-the-better-one/didder/releases/download/v1.1.0/didder_1.1.0_linux_64-bit -O /home/build/bin/didder
    chmod +x ~/bin/didder
    export PATH="$PATH:/home/build/bin"
- package: |
    export PATH="$PATH:/home/build/bin"
    cd nebula
    make build-content
    tar -C site/out -cvz . > ../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz