image: alpine/latest
packages:
  - crystal
  - shards
  - yaml-dev
  - libxml2
oauth: pages.sr.ht/PAGES:RW
environment:
  site: raleighwi.se
sources:
  - https://git.sr.ht/~arcade/nebula
tasks:
- package: |
    cd nebula
    make install-deps-linux
    make
    tar -C www -cvz . > ../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz