[dependencies]
    packages = [
        "crystal",
        "shards",
        "bash"
    ]

    binary_downloads = []

[source]
    dir = "."

[build]
    main = """
mkdir bin
wget https://github.com/makeworld-the-better-one/didder/releases/download/v1.1.0/didder_1.1.0_linux_64-bit -O /home/build/bin/didder
chmod +x ~/bin/didder
export PATH="$PATH:/home/build/bin"
export PATH="$PATH:/home/build/bin"
cd nebula
make build-content
    """
    install = """"""