url: "localhost:8000"
stylesheet: "stylesheet.css"
# black gray white
recolor: "#002b36 #839496 #fdf6e3"
CNAME: "arcades.agency"
author: "Arcade Wise"
comments: "http://134.209.165.242"
desc: "Aethopica"
rss: "feed.rss"