#!/bin/bash

GIT_DIR="/root/nebula"
TARGET="/root/nebulabuilt"

while read oldrev newrev ref
do
    # We gonna do stuff.
    BRANCH=$(git rev-parse --symbolic --abbrev-ref $ref)

        echo "---- Push received! Deploying branch: ${BRANCH}..."

        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH

        cd /root/nebulabuilt
        THREADS="--threads=2" make build-content
        cp -r /root/nebulabuilt/www/* /var/www/html

        echo "--- Deployed to /var/www!"
done